# GitHub Environment Configuration for Production  
name: production
protection_rules:
  required_reviewers:
    - sre-team
    - operations-team
  wait_timer: 300  # 5 minute delay before deployment
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false