# GitHub Environment Configuration for Staging
name: staging
protection_rules:
  required_reviewers:
    - qa-team
  wait_timer: 0
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false